# Generated by Django 3.0.8 on 2020-08-04 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GenEd',
            fields=[
                ('field_id', models.CharField(db_column='_id', max_length=255, primary_key=True, serialize=False)),
                ('course_comb', models.CharField(db_column='Course_Comb', max_length=500)),
                ('course', models.CharField(db_column='Course', max_length=50)),
                ('course_title', models.CharField(db_column='Course_title', max_length=500)),
                ('acp', models.CharField(blank=True, db_column='ACP', max_length=50, null=True)),
                ('cs', models.CharField(blank=True, db_column='CS', max_length=50, null=True)),
                ('hum', models.CharField(blank=True, db_column='HUM', max_length=50, null=True)),
                ('nat', models.CharField(blank=True, db_column='NAT', max_length=50, null=True)),
                ('qr', models.CharField(blank=True, db_column='QR', max_length=50, null=True)),
                ('sbs', models.CharField(blank=True, db_column='SBS', max_length=50, null=True)),
            ],
            options={
                'db_table': 'Gen_ED',
                'managed': False,
            },
        ),
    ]
