# Generated by Django 3.0.8 on 2020-08-05 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentCourseTable',
            fields=[
                ('email', models.CharField(db_column='email_Id', max_length=255)),
                ('field_id', models.CharField(db_column='_id', max_length=120, primary_key=True, serialize=False)),
                ('course_comb', models.CharField(db_column='Course_Comb', max_length=255)),
                ('letter_grade', models.CharField(db_column='Letter_Grade', max_length=300)),
                ('gpa_hours', models.CharField(db_column='GPA_HOURS', max_length=300)),
                ('gpa_quality_points', models.CharField(db_column='GPA_QUALITY_POINTS', max_length=300)),
                ('primary_instructor', models.CharField(db_column='Primary Instructor', max_length=300)),
            ],
            options={
                'db_table': 'Student_Course_Table',
                'managed': False,
            },
        ),
    ]
